name: yin_umeng
description: flutter umeng analysis
version: 0.0.4
homepage: https://github.com/yx544806988/yin_umeng.git

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.yin_umeng
        pluginClass: YinUmengPlugin

