name: yin_umeng
description: flutter umeng analysis
version: 0.0.1
author: yin <yin_8023@163.com>
homepage: https://github.com/yx544806988/yin_umeng.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.yin_umeng
    pluginClass: YinUmengPlugin

